name: ChristmasMiracle
version: 1.0.2-PREALPHA-SNAPSHOT
main: com.gmail.gogobebe2.christmasmiracle.ChristmasMiracle
description: Allows creation of everlasting snow.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
